### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by babA409866** [aGIToz/PyInpaint#1]
Cannot get any result.
 giving a example is pretty good

**Comment by Firdavs-coder** [comment]
Neither can I

**Comment by Firdavs-coder** [comment]
![image](https://user-images.githubusercontent.com/84655445/204804047-fb1583a1-ac81-41dc-a17a-71c7c6a36ec3.png)
it doesnt download anything ?

**Comment by aGIToz** [comment]
Hello! 

Apologies for late reply.

- First, I want to know that if you are able to reproduce the results in the notebooks folder?
- What is the size of the image you are trying to inpaint?
- Could you share the image? May be, I can assist you in choosing the right params.

**Comment by Arilziem** [comment]
I also came across this, but it turned out to be that my mask was inverted (the parts to be inpainted need to be black rather than white). Usually, the '# of pixels to be inpainted' will be in the thousands, not hundreds of thousands.

**Comment by aGIToz** [comment]
@Arilziem  True! In the video on the README at 1:27 I show the mask.

**Comment by madtunebk** [comment]
for me not work at all , i used opencv inpaint function .. but i have a lot artifactic left over.

**Comment by DigitalSurgeX** [comment]
Hi!

I can't seem to get PyInpaint to work, it appears to be having trouble finding my images when they are in the same directory (which I have checked using os, used both direct and relative pathing, etc.) and changing up how I refer to the images doesn't seem to do anything. I am trying to access it through python and have tried the cmd prompt way for insurance.
![cmd](https://github.com/aGIToz/PyInpaint/assets/69163145/49321034-0d33-4c9c-9b96-bdd8efeacdef)
![python-terminal](https://github.com/aGIToz/PyInpaint/assets/69163145/491b7f36-e450-4c15-8fa4-41f5b9c90ce2)

**Comment by DigitalSurgeX** [comment]
PyInpaint didnt seem to work, instead the mask is still in the image and all the colors have become inverted (blue -> orange vice versa). Please help
